//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
public class Main {
    public static void main(String[] args) {
    int itInt = 1;
    byte itByte = -2;
    short itShort = 5;
    long itLong = 24087L;
    float itFloat = 8.5F;
    double itDouble = 8.78;
        System.out.println("Task 1");
        System.out.println("Значение переменной itInt с типом int равно " + itInt);
        System.out.println("Значение переменной itByte с типом byte равно " + itByte);
        System.out.println("Значение переменной itShort с типом short равно " + itShort);
        System.out.println("Значение переменной itLong с типом long равно " + itLong);
        System.out.println("Значение переменной itFloat с типом float равно " + itFloat);
        System.out.println("Значение переменной itDouble с типом double равно " + itDouble);
        System.out.println(" ");
        float a = 27.2F;
        long b = 987678965549L;
        double c = 2.786;
        int d = 569;
        short e = -159;
        short f = 27897;
        int g = 67;
        int studTeacher1 = 23;
        int studTeacher2 = 27;
        int studTeacher3 = 30;
        int allStud = studTeacher1 + studTeacher2 + studTeacher3;
        int forStud = 480 / allStud;
        System.out.println("Task 3");
        System.out.println("На каждого ученика рассчитано " + forStud + " листов бумаги.");
        System.out.println(" ");
        int bottlePerMin = 16 / 2;
        int allBottlers = bottlePerMin * 20;
        System.out.println("Task 4");
        System.out.println("За 20 минут машина произвела " + allBottlers + " штук бутылок.");
        allBottlers = bottlePerMin * 24 * 60;
        System.out.println("За сутки машина произвела " + allBottlers + " штук бутылок.");
        allBottlers = (bottlePerMin * 24 * 60) * 3;
        System.out.println("За 3 дня машина произвела " + allBottlers + " штук бутылок.");
        allBottlers = (bottlePerMin * 24 * 60) * 30;
        System.out.println("За месяц (30 дней) машина произвела " + allBottlers + " штук бутылок.");
        int allClass = 120 / 6;
        int whitePaint = allClass * 2;
        int brownPaint = allClass * 4;
        System.out.println(" ");
        System.out.println("Task 5");
        System.out.println("В школе, где " +allClass + " классов, нужно " + whitePaint + " банок белой краски и " + brownPaint + " банок коричневой краски.");
        int bananasQuantity = 5;
        float oneBananasWeight = 80F;
        float allBananasWeight = oneBananasWeight * bananasQuantity;
        int milkVolume = 200;
        float oneHundredMilkWeight = 105F;
        float allMilkWeight = oneHundredMilkWeight * milkVolume / 100;
        int iceCreamQuantity = 2;
        float oneIceCreamWeight = 100F;
        float allIceCreamWeight = oneIceCreamWeight * iceCreamQuantity;
        int eggsQuantity = 4;
        float oneEggsWeight = 70F;
        float allEggsWeight = oneEggsWeight * eggsQuantity;
        float allWeight = allBananasWeight + allMilkWeight + allIceCreamWeight + allEggsWeight;
        System.out.println(" ");
        System.out.println("Task 6");
        System.out.println("Весь вес " + allWeight + " грамм.");
        allWeight = allWeight / 1000;
        System.out.println("Весь вес " + allWeight + " килограмм.");
        int needWeigh = 7;
        int minWeigh = 250;
        int maxWeigh = 500;
        int daysMinWeight = needWeigh * 1000 / minWeigh;
        int daysMaxWeight = needWeigh * 1000 / maxWeigh;
        System.out.println(" ");
        System.out.println("Task 7");
        System.out.println("Для снижения веса спортсмена на 7 килограмм, понадобится " + daysMinWeight + " дней, если терять по " + minWeigh + " грамм,");
        System.out.println(" и " + daysMaxWeight + " дней, если терять по " + maxWeigh + " грамм.");
        double monthSalaryMasha = 67760;
        double monthUpSalaryMasha = monthSalaryMasha / 100 * 10 + monthSalaryMasha;
        double yearUpSalaryMasha = monthUpSalaryMasha * 12;
        double monthSalaryDenis = 83690;
        double monthUpSalaryDenis = monthSalaryDenis / 100 * 10 + monthSalaryDenis;
        double yearUpSalaryDenis = monthUpSalaryDenis * 12;
        double monthSalaryKristina = 76230;
        double monthUpSalaryKristina = monthSalaryKristina / 100 * 10 + monthSalaryKristina;
        double yearUpSalaryKristina = monthUpSalaryKristina * 12;
        System.out.println(" ");
        System.out.println("Task 8");
        System.out.println("Маша теперь получает " + monthUpSalaryMasha + " рублей. Годовой доход был " + monthSalaryMasha * 12 + " рублей, а теперь стал " + yearUpSalaryMasha + " рублей. Разница в " + (yearUpSalaryMasha - monthSalaryMasha * 12) + " рублей.");
        System.out.println("Денис теперь получает " + monthUpSalaryDenis + " рублей. Годовой доход был " + monthSalaryDenis * 12 + " рублей, а теперь стал " + yearUpSalaryDenis + " рублей. Разница в " + (yearUpSalaryDenis - monthSalaryDenis * 12) + " рублей.");
        System.out.println("Кристина теперь получает " + monthUpSalaryKristina + " рублей. Годовой доход " + monthSalaryKristina * 12 + "рублей, а теперь стал " + yearUpSalaryKristina + " рублей. Разница в " + (yearUpSalaryKristina - monthSalaryKristina * 12) + " рублей.");
    }
}